### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by oldium** [fakundo/react-localized#4]
Would it be possible to update the code to work with React 18, please?

Currently there is following warning printed when used with React 18 (those are written by React):

* Warning: useEffect must not return anything besides a function, which is used for clean-up. It looks like you wrote useEffect(async () => ...) or returned a Promise. Instead, write the async function inside your effect and call it immediately:

```
useEffect(() => {
  async function fetchData() {
    // You can await here
    const response = await MyAPI.getData(someId);
    // ...
  }
  fetchData();
}, [someId]); // Or [] if effect doesn't need props or state
```

**Comment by fakundo** [comment]
Fixed! Thank you!
